import pg from 'pg';
import type { Pool } from 'pg';

const { Pool: PgPool } = pg;

// bigint (OID 20) columns -- id, thread_no, post_no, ts_utc, and any
// COUNT(*)/MIN/MAX over them -- come back from node-postgres as strings by
// default, to avoid silent precision loss beyond Number.MAX_SAFE_INTEGER.
// Values here stay far below that (566M rows today), so parsing them back
// to plain numbers is safe and matches what SQLite always handed back.
pg.types.setTypeParser(20, (v: string) => parseInt(v, 10));

const SCHEMA = `
-- completed_at records that a source's adapter returned NORMALLY, which is
-- not the same as "this source has rows": 4chan-threads once aborted 13.5M
-- posts deep on a NUL byte, and anything keyed on row count would have
-- wrongly called that done. Only a clean return sets it, and any throw leaves
-- it null so the next run picks the source up again.
--
-- It is also not permanent. Re-staging an archive, or fixing an adapter bug
-- that silently dropped rows, means the old completion no longer describes
-- what a run would produce -- ingest-all --redo <source> re-ingests anyway
-- and refreshes the timestamp on the way out.
CREATE TABLE IF NOT EXISTS sources (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL UNIQUE,
  link         TEXT,
  notes        TEXT,
  completed_at TIMESTAMPTZ
);

-- CREATE TABLE IF NOT EXISTS is a no-op on a store that predates the column,
-- so add it separately rather than silently leaving those stores without it.
ALTER TABLE sources ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;

-- One row per post, not per (post, archive). source_id records which archive
-- first supplied the row; a later archive holding the same post is skipped by
-- the UNIQUE constraint rather than stored again.
--
-- Overlap between archives is therefore NOT answerable from this table. That
-- is deliberate: aggregate queries (word frequency over a period, posts per
-- year) would otherwise double-count posts held by several archives, and
-- overlap is better inferred by diffing the source datasets themselves.
CREATE TABLE IF NOT EXISTS posts (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id      INTEGER NOT NULL REFERENCES sources(id),
  site           TEXT NOT NULL,
  board          TEXT NOT NULL,
  thread_no      BIGINT NOT NULL,
  post_no        BIGINT NOT NULL,
  is_op          BOOLEAN NOT NULL DEFAULT FALSE,
  ts_utc         BIGINT,
  name           TEXT,
  tripcode       TEXT,
  subject        TEXT,
  body_text      TEXT,
  media_filename TEXT,
  media_md5      TEXT,
  -- 'simple' config: no stemming, no stopword removal -- matches FTS5's
  -- unicode61 tokenizer fidelity. Swapping configs later means dropping and
  -- recreating this column (comparable cost to FTS5's old
  -- posts_fts(posts_fts) VALUES('rebuild')).
  search_vector  tsvector GENERATED ALWAYS AS (
                   to_tsvector('simple', coalesce(subject, '') || ' ' || coalesce(body_text, ''))
                 ) STORED,
  UNIQUE (site, board, post_no)
);

-- NOTE: the query-time indexes on posts are deliberately NOT here -- see
-- QUERY_INDEXES below. What remains is only what ingest itself needs: the
-- primary key, and the UNIQUE constraint that ON CONFLICT targets.

-- Rolled-up post counts, maintained during ingest.
--
-- Deriving these from the posts table means walking the index for every
-- board: a plain "which boards exist" GROUP BY costs ~215s on a 288M-row
-- store, and a per-board year grid tens of seconds. Keyed by year as well
-- as board so one table answers both the board list and the coverage
-- charts.
--
-- year is the UTC calendar year; posts with no timestamp are counted under
-- year IS NULL so the totals still reconcile with the posts table.
--
-- Since posts holds one row per post, these counts no longer double-count
-- across archives: SUM(posts) equals COUNT(*) FROM posts, and source_id
-- attributes each post to whichever archive supplied it first.
CREATE TABLE IF NOT EXISTS post_stats (
  source_id INTEGER NOT NULL REFERENCES sources(id),
  site      TEXT NOT NULL,
  board     TEXT NOT NULL,
  year      INTEGER,
  posts     BIGINT NOT NULL DEFAULT 0,
  min_ts    BIGINT,
  max_ts    BIGINT
);

-- year is nullable (undated posts), but PRIMARY KEY forces NOT NULL in
-- Postgres (unlike SQLite, which let this be a non-rowid PK with nulls) --
-- COALESCE the uniqueness expression instead of using a real PK, and target
-- the same expression from ON CONFLICT.
CREATE UNIQUE INDEX IF NOT EXISTS post_stats_key
  ON post_stats (source_id, site, board, COALESCE(year, -1));

CREATE INDEX IF NOT EXISTS idx_post_stats_board
  ON post_stats (site, board, year);
`;

/**
 * Indexes that only queries need, kept out of `SCHEMA` on purpose.
 *
 * `openDb` runs `SCHEMA` on every connect, which is fine for cheap DDL but
 * catastrophic for these: on a 288M-row store they are ~72GB, and any command
 * that opened a pool would silently rebuild whatever had been dropped. Worse,
 * ingest pays for them on *every insert* while getting nothing back -- only
 * the UNIQUE constraint matters to ON CONFLICT. Measured on the last full
 * pass, GIN pending-list merges alone accounted for 1.01 billion of the 1.02
 * billion index blocks read from disk (99.4%).
 *
 * So the lifecycle is explicit: `indexes drop`, ingest, `indexes build`.
 * Building from a finished table is a sort, not 500M random index updates.
 *
 * These land in the database's default tablespace, which is the SSD -- the
 * `posts` heap lives in the `slow` tablespace on the array. Index reads are
 * random and want the SSD; heap writes during ingest are sequential appends
 * and do not.
 */
export const QUERY_INDEXES: { name: string; sql: string }[] = [
  {
    name: 'idx_posts_board_ts',
    sql: 'CREATE INDEX IF NOT EXISTS idx_posts_board_ts ON posts (site, board, ts_utc)',
  },
  {
    // covering index for the list/stats queries: distinct post/thread counts
    // and date spans per board without touching the (body-text-heavy) rows
    name: 'idx_posts_stats',
    sql: 'CREATE INDEX IF NOT EXISTS idx_posts_stats ON posts (site, board, post_no, thread_no, ts_utc)',
  },
  {
    name: 'idx_posts_src_ts',
    sql: 'CREATE INDEX IF NOT EXISTS idx_posts_src_ts ON posts (source_id, ts_utc)',
  },
  {
    // gin_pending_list_limit is in kB (262144 = 256MB), not a unit string.
    // GIN buffers new entries in a pending list and periodically merges it
    // into the index proper; at the default 4MB that merge runs constantly
    // over scattered pages. A larger list trades fewer, larger, more
    // sequential merges for slower searches while the list is unmerged --
    // the right side of that trade, since searches happen after ingest.
    //
    // IF NOT EXISTS means this does NOT reach an index that already exists.
    // On a store built before this setting, apply it by hand:
    //   ALTER INDEX idx_posts_search SET (gin_pending_list_limit = 262144);
    name: 'idx_posts_search',
    sql:
      'CREATE INDEX IF NOT EXISTS idx_posts_search ON posts USING GIN (search_vector)' +
      ' WITH (gin_pending_list_limit = 262144)',
  },
];

/** Which query indexes currently exist, with their on-disk sizes. */
export const queryIndexStatus = async (
  db: Pool
): Promise<{ name: string; exists: boolean; bytes: number }[]> => {
  const { rows } = await db.query<{ relname: string; bytes: number }>(
    `SELECT c.relname, pg_relation_size(c.oid)::bigint AS bytes
       FROM pg_class c
      WHERE c.relkind = 'i' AND c.relname = ANY($1)`,
    [QUERY_INDEXES.map((i) => i.name)]
  );
  const found = new Map(rows.map((r) => [r.relname, r.bytes]));
  return QUERY_INDEXES.map((i) => ({
    name: i.name,
    exists: found.has(i.name),
    bytes: found.get(i.name) ?? 0,
  }));
};

/**
 * Server-level settings that matter for ingest, recorded here because no
 * amount of DDL can express them -- they are cluster-wide, not schema, so
 * `openDb` cannot apply them and a fresh store will NOT pick them up.
 * Apply once per server, as a superuser:
 *
 *   ALTER SYSTEM SET max_wal_size = 16384;              -- MB
 *   ALTER SYSTEM SET checkpoint_completion_target = 0.9;
 *   SELECT pg_reload_conf();                            -- no restart needed
 *
 *   ALTER SYSTEM SET shared_buffers = '16GB';           -- needs a RESTART
 *
 * maintenance_work_mem stays modest globally (256MB) because autovacuum_work_mem
 * inherits it, and three autovacuum workers each claiming several GB is not
 * what you want running alongside an ingest. `indexes build` raises it for its
 * own session instead, which is where it actually matters.
 *
 * At the stock Docker defaults (max_wal_size 1GB, shared_buffers 128MB) a
 * bulk ingest blows through the WAL budget every few seconds and forces a
 * checkpoint: measured mid-run, 2355 *requested* checkpoints against 18
 * scheduled ones, with backends stalling on LWLock:WALWrite. Raising
 * max_wal_size stopped the storm outright (zero forced checkpoints in the
 * next four minutes).
 *
 * Be aware it bought only ~7% throughput (5.88M -> 6.30M rows/hour): the
 * checkpoint storm was real but was not the bottleneck. That turned out to
 * be GIN pending-list merges -- see the note on idx_posts_search above.
 * Recorded so the next person does not re-run the same experiment and
 * conclude, wrongly, that checkpointing is where the time goes.
 */

export const openDb = async (connectionString: string): Promise<Pool> => {
  const pool = new PgPool({
    connectionString,
    max: 5,
    connectionTimeoutMillis: 10_000,
    // Date-bucketing (to_char(to_timestamp(...))) assumes UTC; don't rely on
    // whatever timezone the server defaults to. Set via the startup packet
    // rather than a query fired from a "connect" handler -- that handler
    // can't be awaited before the pool hands the same client to whichever
    // query is next in line, racing two queries on one connection (pg
    // deprecated and will remove the queuing behaviour that happens to make
    // that "work" today).
    options: '-c TimeZone=UTC',
  });
  // A NAS-hosted connection can drop; without this handler that surfaces as
  // an uncaught exception and crashes the process instead of just failing
  // the query that was using it.
  pool.on('error', (err) => {
    console.error('unexpected error on idle postgres client', err);
  });
  await pool.query(SCHEMA);
  return pool;
};

export const getOrCreateSource = async (
  db: Pool,
  name: string,
  link?: string
): Promise<number> => {
  await db.query(
    'INSERT INTO sources (name, link) VALUES ($1, $2) ON CONFLICT (name) DO NOTHING',
    [name, link ?? null]
  );
  const { rows } = await db.query<{ id: number }>(
    'SELECT id FROM sources WHERE name = $1',
    [name]
  );
  if (!rows[0]) throw new Error(`failed to create source ${name}`);
  return rows[0].id;
};

/**
 * Record that a source's adapter ran to a clean return.
 *
 * Call this only from the caller of the adapter, after it returns -- never
 * from inside one. An adapter that throws part-way has still written rows,
 * and marking on anything short of a normal return would record progress
 * rather than completion.
 */
export const markSourceCompleted = async (
  db: Pool,
  sourceId: number
): Promise<void> => {
  await db.query('UPDATE sources SET completed_at = now() WHERE id = $1', [
    sourceId,
  ]);
};

/** Manifest `name`s already completed, mapped to when. */
export const completedSources = async (
  db: Pool
): Promise<Map<string, Date>> => {
  const { rows } = await db.query<{ name: string; completed_at: Date }>(
    'SELECT name, completed_at FROM sources WHERE completed_at IS NOT NULL'
  );
  return new Map(rows.map((r) => [r.name, r.completed_at]));
};
