import pg from "pg";
import type { Pool } from "pg";

const { Pool: PgPool } = pg;

// bigint (OID 20) columns -- id, thread_no, post_no, ts_utc, and any
// COUNT(*)/MIN/MAX over them -- come back from node-postgres as strings by
// default, to avoid silent precision loss beyond Number.MAX_SAFE_INTEGER.
// Values here stay far below that (566M rows today), so parsing them back
// to plain numbers is safe and matches what SQLite always handed back.
pg.types.setTypeParser(20, (v: string) => parseInt(v, 10));

const SCHEMA = `
CREATE TABLE IF NOT EXISTS sources (
  id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  TEXT NOT NULL UNIQUE,
  link  TEXT,
  notes TEXT
);

-- One row per post, not per (post, archive). source_id records which archive
-- first supplied the row; a later archive holding the same post is skipped by
-- the UNIQUE constraint rather than stored again.
--
-- Overlap between archives is therefore NOT answerable from this table. That
-- is deliberate: aggregate queries (word frequency over a period, posts per
-- year) would otherwise double-count posts held by several archives, and
-- overlap is better inferred by diffing the source datasets themselves.
CREATE TABLE IF NOT EXISTS posts (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id      INTEGER NOT NULL REFERENCES sources(id),
  site           TEXT NOT NULL,
  board          TEXT NOT NULL,
  thread_no      BIGINT NOT NULL,
  post_no        BIGINT NOT NULL,
  is_op          BOOLEAN NOT NULL DEFAULT FALSE,
  ts_utc         BIGINT,
  name           TEXT,
  tripcode       TEXT,
  subject        TEXT,
  body_text      TEXT,
  media_filename TEXT,
  media_md5      TEXT,
  -- 'simple' config: no stemming, no stopword removal -- matches FTS5's
  -- unicode61 tokenizer fidelity. Swapping configs later means dropping and
  -- recreating this column (comparable cost to FTS5's old
  -- posts_fts(posts_fts) VALUES('rebuild')).
  search_vector  tsvector GENERATED ALWAYS AS (
                   to_tsvector('simple', coalesce(subject, '') || ' ' || coalesce(body_text, ''))
                 ) STORED,
  UNIQUE (site, board, post_no)
);

CREATE INDEX IF NOT EXISTS idx_posts_board_ts ON posts (site, board, ts_utc);

-- covering index for the list/stats queries: distinct post/thread counts and
-- date spans per board without touching the (body-text-heavy) table rows
CREATE INDEX IF NOT EXISTS idx_posts_stats
  ON posts (site, board, post_no, thread_no, ts_utc);

CREATE INDEX IF NOT EXISTS idx_posts_src_ts ON posts (source_id, ts_utc);

-- GIN buffers new entries in a "pending list" and periodically merges it into
-- the index proper. At the default 4MB that merge runs constantly and touches
-- scattered pages, and it dominates everything else during a bulk ingest:
-- measured mid-run at 225M rows, this one index accounted for 1.01 billion of
-- the 1.02 billion index blocks read from disk (99.4%), sitting at a 74.9%
-- cache hit rate while every other index on posts held 99-100%. A larger
-- pending list trades fewer, larger, more sequential merges for slower
-- searches while the list is unmerged -- the right side of that trade here,
-- since ingest is write-heavy and searches happen afterwards.
--
-- NOTE: IF NOT EXISTS means this clause does NOT reach an index that already
-- exists. On a store created before this line, apply it by hand:
--   ALTER INDEX idx_posts_search SET (gin_pending_list_limit = 262144);
CREATE INDEX IF NOT EXISTS idx_posts_search ON posts USING GIN (search_vector)
  WITH (gin_pending_list_limit = 262144);  -- kB, i.e. 256MB

-- Rolled-up post counts, maintained during ingest.
--
-- Deriving these from the posts table means walking the index for every
-- board: a plain "which boards exist" GROUP BY costs ~215s on a 288M-row
-- store, and a per-board year grid tens of seconds. Keyed by year as well
-- as board so one table answers both the board list and the coverage
-- charts.
--
-- year is the UTC calendar year; posts with no timestamp are counted under
-- year IS NULL so the totals still reconcile with the posts table.
--
-- Since posts holds one row per post, these counts no longer double-count
-- across archives: SUM(posts) equals COUNT(*) FROM posts, and source_id
-- attributes each post to whichever archive supplied it first.
CREATE TABLE IF NOT EXISTS post_stats (
  source_id INTEGER NOT NULL REFERENCES sources(id),
  site      TEXT NOT NULL,
  board     TEXT NOT NULL,
  year      INTEGER,
  posts     BIGINT NOT NULL DEFAULT 0,
  min_ts    BIGINT,
  max_ts    BIGINT
);

-- year is nullable (undated posts), but PRIMARY KEY forces NOT NULL in
-- Postgres (unlike SQLite, which let this be a non-rowid PK with nulls) --
-- COALESCE the uniqueness expression instead of using a real PK, and target
-- the same expression from ON CONFLICT.
CREATE UNIQUE INDEX IF NOT EXISTS post_stats_key
  ON post_stats (source_id, site, board, COALESCE(year, -1));

CREATE INDEX IF NOT EXISTS idx_post_stats_board
  ON post_stats (site, board, year);
`;

/**
 * Server-level settings that matter for ingest, recorded here because no
 * amount of DDL can express them -- they are cluster-wide, not schema, so
 * `openDb` cannot apply them and a fresh store will NOT pick them up.
 * Apply once per server, as a superuser:
 *
 *   ALTER SYSTEM SET max_wal_size = 16384;              -- MB
 *   ALTER SYSTEM SET checkpoint_completion_target = 0.9;
 *   SELECT pg_reload_conf();                            -- no restart needed
 *
 *   ALTER SYSTEM SET shared_buffers = '4GB';            -- needs a RESTART
 *
 * At the stock Docker defaults (max_wal_size 1GB, shared_buffers 128MB) a
 * bulk ingest blows through the WAL budget every few seconds and forces a
 * checkpoint: measured mid-run, 2355 *requested* checkpoints against 18
 * scheduled ones, with backends stalling on LWLock:WALWrite. Raising
 * max_wal_size stopped the storm outright (zero forced checkpoints in the
 * next four minutes).
 *
 * Be aware it bought only ~7% throughput (5.88M -> 6.30M rows/hour): the
 * checkpoint storm was real but was not the bottleneck. That turned out to
 * be GIN pending-list merges -- see the note on idx_posts_search above.
 * Recorded so the next person does not re-run the same experiment and
 * conclude, wrongly, that checkpointing is where the time goes.
 */

export const openDb = async (connectionString: string): Promise<Pool> => {
  const pool = new PgPool({
    connectionString,
    max: 5,
    connectionTimeoutMillis: 10_000,
    // Date-bucketing (to_char(to_timestamp(...))) assumes UTC; don't rely on
    // whatever timezone the server defaults to. Set via the startup packet
    // rather than a query fired from a "connect" handler -- that handler
    // can't be awaited before the pool hands the same client to whichever
    // query is next in line, racing two queries on one connection (pg
    // deprecated and will remove the queuing behaviour that happens to make
    // that "work" today).
    options: "-c TimeZone=UTC",
  });
  // A NAS-hosted connection can drop; without this handler that surfaces as
  // an uncaught exception and crashes the process instead of just failing
  // the query that was using it.
  pool.on("error", (err) => {
    console.error("unexpected error on idle postgres client", err);
  });
  await pool.query(SCHEMA);
  return pool;
};

export const getOrCreateSource = async (
  db: Pool,
  name: string,
  link?: string,
): Promise<number> => {
  await db.query(
    "INSERT INTO sources (name, link) VALUES ($1, $2) ON CONFLICT (name) DO NOTHING",
    [name, link ?? null],
  );
  const { rows } = await db.query<{ id: number }>(
    "SELECT id FROM sources WHERE name = $1",
    [name],
  );
  if (!rows[0]) throw new Error(`failed to create source ${name}`);
  return rows[0].id;
};
