import pg from "pg";
import type { Pool } from "pg";

const { Pool: PgPool } = pg;

// bigint (OID 20) columns -- id, thread_no, post_no, ts_utc, and any
// COUNT(*)/MIN/MAX over them -- come back from node-postgres as strings by
// default, to avoid silent precision loss beyond Number.MAX_SAFE_INTEGER.
// Values here stay far below that (566M rows today), so parsing them back
// to plain numbers is safe and matches what SQLite always handed back.
pg.types.setTypeParser(20, (v: string) => parseInt(v, 10));

const SCHEMA = `
CREATE TABLE IF NOT EXISTS sources (
  id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  TEXT NOT NULL UNIQUE,
  link  TEXT,
  notes TEXT
);

-- One row per post, not per (post, archive). source_id records which archive
-- first supplied the row; a later archive holding the same post is skipped by
-- the UNIQUE constraint rather than stored again.
--
-- Overlap between archives is therefore NOT answerable from this table. That
-- is deliberate: aggregate queries (word frequency over a period, posts per
-- year) would otherwise double-count posts held by several archives, and
-- overlap is better inferred by diffing the source datasets themselves.
CREATE TABLE IF NOT EXISTS posts (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id      INTEGER NOT NULL REFERENCES sources(id),
  site           TEXT NOT NULL,
  board          TEXT NOT NULL,
  thread_no      BIGINT NOT NULL,
  post_no        BIGINT NOT NULL,
  is_op          BOOLEAN NOT NULL DEFAULT FALSE,
  ts_utc         BIGINT,
  name           TEXT,
  tripcode       TEXT,
  subject        TEXT,
  body_text      TEXT,
  media_filename TEXT,
  media_md5      TEXT,
  -- 'simple' config: no stemming, no stopword removal -- matches FTS5's
  -- unicode61 tokenizer fidelity. Swapping configs later means dropping and
  -- recreating this column (comparable cost to FTS5's old
  -- posts_fts(posts_fts) VALUES('rebuild')).
  search_vector  tsvector GENERATED ALWAYS AS (
                   to_tsvector('simple', coalesce(subject, '') || ' ' || coalesce(body_text, ''))
                 ) STORED,
  UNIQUE (site, board, post_no)
);

CREATE INDEX IF NOT EXISTS idx_posts_board_ts ON posts (site, board, ts_utc);

-- covering index for the list/stats queries: distinct post/thread counts and
-- date spans per board without touching the (body-text-heavy) table rows
CREATE INDEX IF NOT EXISTS idx_posts_stats
  ON posts (site, board, post_no, thread_no, ts_utc);

CREATE INDEX IF NOT EXISTS idx_posts_src_ts ON posts (source_id, ts_utc);

CREATE INDEX IF NOT EXISTS idx_posts_search ON posts USING GIN (search_vector);

-- Rolled-up post counts, maintained during ingest.
--
-- Deriving these from the posts table means walking the index for every
-- board: a plain "which boards exist" GROUP BY costs ~215s on a 288M-row
-- store, and a per-board year grid tens of seconds. Keyed by year as well
-- as board so one table answers both the board list and the coverage
-- charts.
--
-- year is the UTC calendar year; posts with no timestamp are counted under
-- year IS NULL so the totals still reconcile with the posts table.
--
-- Since posts holds one row per post, these counts no longer double-count
-- across archives: SUM(posts) equals COUNT(*) FROM posts, and source_id
-- attributes each post to whichever archive supplied it first.
CREATE TABLE IF NOT EXISTS post_stats (
  source_id INTEGER NOT NULL REFERENCES sources(id),
  site      TEXT NOT NULL,
  board     TEXT NOT NULL,
  year      INTEGER,
  posts     BIGINT NOT NULL DEFAULT 0,
  min_ts    BIGINT,
  max_ts    BIGINT
);

-- year is nullable (undated posts), but PRIMARY KEY forces NOT NULL in
-- Postgres (unlike SQLite, which let this be a non-rowid PK with nulls) --
-- COALESCE the uniqueness expression instead of using a real PK, and target
-- the same expression from ON CONFLICT.
CREATE UNIQUE INDEX IF NOT EXISTS post_stats_key
  ON post_stats (source_id, site, board, COALESCE(year, -1));

CREATE INDEX IF NOT EXISTS idx_post_stats_board
  ON post_stats (site, board, year);
`;

export const openDb = async (connectionString: string): Promise<Pool> => {
  const pool = new PgPool({
    connectionString,
    max: 5,
    connectionTimeoutMillis: 10_000,
    // Date-bucketing (to_char(to_timestamp(...))) assumes UTC; don't rely on
    // whatever timezone the server defaults to. Set via the startup packet
    // rather than a query fired from a "connect" handler -- that handler
    // can't be awaited before the pool hands the same client to whichever
    // query is next in line, racing two queries on one connection (pg
    // deprecated and will remove the queuing behaviour that happens to make
    // that "work" today).
    options: "-c TimeZone=UTC",
  });
  // A NAS-hosted connection can drop; without this handler that surfaces as
  // an uncaught exception and crashes the process instead of just failing
  // the query that was using it.
  pool.on("error", (err) => {
    console.error("unexpected error on idle postgres client", err);
  });
  await pool.query(SCHEMA);
  return pool;
};

export const getOrCreateSource = async (
  db: Pool,
  name: string,
  link?: string,
): Promise<number> => {
  await db.query(
    "INSERT INTO sources (name, link) VALUES ($1, $2) ON CONFLICT (name) DO NOTHING",
    [name, link ?? null],
  );
  const { rows } = await db.query<{ id: number }>(
    "SELECT id FROM sources WHERE name = $1",
    [name],
  );
  if (!rows[0]) throw new Error(`failed to create source ${name}`);
  return rows[0].id;
};
